id: P010382
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:46:57.594255
source_metadata:
  id: bdr:W1KG15990
  title: ཕར་ཕྱིན་དགོངས་དཔྱོད་གཟུར་གནས་ཀུནྡ་བཞད་པའི་འཛུམ་ཟེར།
  author: ''
  volumes:
    730f4ec05cfa4f33a17e00798417e4e4:
      image_group_id: I1KG16199
      title: ''
      volume_number: 1
      total_pages: 382
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
